export const GET_USERS = 'GET_USERS';
export const USER_LOADED = 'USER_LOADED';
export const SEND_SUCCESS = "SEND_SUCCESS";
export const SEND_FAIL = "SEND_FAIL";
export const ADD_USER = "ADD-USER";
export const DELETE_USER = "DELETE_USER";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_USER = "UPDATE_USER";
export const FILTER_USERS = "FILTER_USERS";
export const CLEAR_USERS = 'CLEAR_USERS';
export const USER_ERROR = "CONTACT_ERROR";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const ADD_APPRAISAL = "ADD_APPRAISAL";
export const UPDATE_APPRAISAL = "UPDATE_APPRAISAL";
export const APPRAISAL_LOADED = "APPRAISAL_LOADED";
export const GET_APPRAISALS = "GET_APPRAISALS";
export const DELETE_APPRAISAL = "DELETE_APPRAISAL";
export const APPRAISAL_ERROR = "APPRAISAL_ERROR";



export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";